/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as IndexRouteImport } from './routes/index'

const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/strategies': typeof StrategiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/strategies': typeof StrategiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtest': typeof BacktestRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/strategies': typeof StrategiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backtest' | '/portfolio' | '/profile' | '/strategies'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/backtest' | '/portfolio' | '/profile' | '/strategies'
  id: '__root__' | '/' | '/backtest' | '/portfolio' | '/profile' | '/strategies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestRoute: typeof BacktestRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  StrategiesRoute: typeof StrategiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestRoute: BacktestRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  StrategiesRoute: StrategiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
